Chain state initialisation
mlabs-haskell/hedgehog-plutus-simple pull request #49
Opened 2023-02-27 16:03 UTC by AriFordsham

2023-02-27 16:04 UTC, AriFordsham commented
The monad code could do with a bit of tidying - it might need a monad transformer somewhere.

@Geometer1729 let me know what you think.

2023-02-27 17:07 UTC, Geometer1729 requested changes
Other than the `(Plutus.CurrencySymbol "NFT")` LGTM

2023-02-27 17:07 UTC, Geometer1729 commented on examples/Spec.hs
> +nft = Plutus.singleton (Plutus.CurrencySymbol "NFT") "" 1
The `IsString` instance for `BuiltinBytestring` attempts to decode a hex string so this probably needs to be a valid hex string and might need to be the correct length for a currency symbol (28 bytes or 56 hex characters) to not throw any weird errors.

2023-03-01 14:43 UTC, Geometer1729 commented
I'm afraid the token name is also a hex string.

2023-03-01 14:47 UTC, AriFordsham commented
It has a custom `IsString` instance that encodes it correctly - http://localhost:8080/plutus-ledger-api/html/src/PlutusLedgerApi.V1.Value.html#TokenName:~:text=Doesn%27t%20verify%20length.-,instance,-IsString%20TokenName%20where

Currency symbols are a hash, so are pseudo-random bytestrings, whilst token names are dev-defined and intended to be human-readable.

2023-03-01 15:14 UTC, Geometer1729 commented
> It has a custom `IsString` instance that encodes it correctly - http://localhost:8080/plutus-ledger-api/html/src/PlutusLedgerApi.V1.Value.html#TokenName:~:text=Doesn%27t%20verify%20length.-,instance,-IsString%20TokenName%20where
> 
> Currency symbols are a hash, so are pseudo-random bytestrings, whilst token names are dev-defined and intended to be human-readable.

Oh okay, sorry about that.

2023-03-01 15:14 UTC, Geometer1729 approved these changes
LGTM

2023-03-01 15:17 UTC, merged